<!DOCTYPE html>
<html>
<head>
<title>Note</title>
<link rel="stylesheet" type="text/css" href="/css/userpage.css" />
<meta charset='utf-8'>
</head>
<body>
	<div id="header">
		<div class="container clearfix">
			<div id="logo">
				<h2>Note</h2>
				<h1>
					<span></span>
					<a href=""><?php echo $this->username;?></a>
				</h1>
			</div>
		</div>
	</div><!-- End of header -->

	<div id="navigation">
		<div class="container clearfix" id="NoteX">
			<ul class="pages">
				<li class="current_page_item">
					<a href="#" title="index">首页</a>
				</li>
				<li>
					<a href="/user/list">Note</a>
				</li>
				<li>
					<a href="/user/edit">新建Note</a>
				</li>
			</ul>
		</div>
	</div><!-- End of navigation -->
	<?php if($this->flag == true){?>
	<div class="clearfix" id="main-content">
		<div id="container">
			<div id="col-580">
				<div class="main section" id="main">
					<div class="widget Blog" id="Blog1">
						<div class="blog-posts hfeed">
							<div class="post hentry uncustomized-post-template">
								<div class="post-meta clearfix">
									<h3 class="post-title left">
										<a href="/user/view-blog/blogid/<?php echo $this->newblog['blogid'];?>"><?php echo $this->newblog['title']?></a>
									</h3>
									
								</div>
								<div class="post-box">
									<div class="post-content">
										<div class="comment-count">
											<?php echo $this->newblog['time'];?>
										</div>
										<span class="post-backlinks post-comment-link"></span>
										<div class="post-body entry-content">
											<pre><?php echo $this->newblog['content'];?></pre>
											<div style="clear: both;"></div>
										</div>
									</div>
								</div>								
							</div>
						</div>
						
					</div>
				</div>
			</div>
			<div class="col-340 right">
				<div id="sidebar">
					<div class="sidebarsec section" id="sidebarsec">
						<div class="widget LinkList" id="LinkList1">
							<h2>最近Note</h2>
							<div class="widget-content">
								<ul>
								<?php foreach ($this->bloglist as $i=>$blog){?>
								<li><a href="/user/view-blog/blogid/<?php echo $blog['blogid'];?>"><?php echo $blog['title']?></a></li>
								<?php }?>
								</ul>
								<div class="clear"></div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php }else{?>
	<p>还没有Note!?</p>
	<p>赶快来新建一个Note吧！</p>
	<div id="button_div"><button id="create_note" class="btn" onclick="window.location.href='/user/edit'">新建Note！</button></div>
	<?php }?>
</body>


</html>