<!DOCTYPE html>
<html>
<head>
<title>Note</title>
<link rel="stylesheet" type="text/css" href="/css/userpage.css" />
<meta charset='utf-8'>
</head>
<body>
	<div id="header">
		<div class="container clearfix">
			<div id="logo">
				<h2>Note</h2>
				<h1>
					<span></span>
					<a href=""><?php echo $this->username;?></a>
				</h1>
			</div>
		</div>
	</div><!-- End of header -->

	<div id="navigation">
		<div class="container clearfix" id="NoteX">
			<ul class="pages">
				<li class="current_page_item">
					<a href="#" title="index">首页</a>
				</li>
				<li>
					<a href="/user/list">Note</a>
				</li>
				<li>
					<a href="/user/edit">新建Note</a>
				</li>
			</ul>
		</div>
	</div><!-- End of navigation -->
	
	<div class="clearfix" id="main-content">
		<div id="container">
			<div id="col-580">
				<div class="main section" id="main">
					<div class="widget Blog" id="Blog1">
						<div class="blog-posts hfeed">
							<div class="post hentry uncustomized-post-template">
								<div class="post-meta clearfix">
									<h3 class="post-title left">
										<a href="/">XXXXXXXXXXXXXXXX</a>
									</h3>
									
								</div>
								<div class="post-box">
									<div class="post-content">
										<div class="comment-count">
											11 comments
										</div>
										<span class="post-backlinks post-comment-link"></span>
										<div class="post-body entry-content">
											
											<p>Magazeen es el nombre de esta plantilla para Blogger adaptada porZona Cerebral. El diseño original del theme corresponde a Function.
											<br><br>El template cuya página de demostración estás viendo ahora mismo, se comparte de forma gratuita bajo licencia Creative Commons 3.0 Reconocimiento, No Comercial y Compartir bajo la misma Licencia. Por tanto, el único requisito exigido para instalarla es mantener los créditos hacia el autor de la obra y hacia Zona Cerebral.</p>
											<div style="clear: both;"></div>
										</div>
									</div>
								</div>								
							</div>
						</div>
						
					</div>
				</div>
			</div>
			<div class="col-340 right">
				<div id="sidebar">
					<div class="sidebarsec section" id="sidebarsec">
						<div class="widget LinkList" id="LinkList1">
							<h2>最近Note</h2>
							<div class="widget-content">
								<ul>
								<li><a href="http://blogsindependientes.com/">Blogs Independientes</a></li>
								<li><a href="http://forosdelblog.com/">Foro para bloggers</a></li>
								<li><a href="http://wefunction.com/">Function</a></li>
								<li><a href="http://zonacerebral.com/">Plantillas Blogger</a></li>
								<li><a href="http://smashingmagazine.com/">Smashing Magazine</a></li>
								<li><a href="http://videoblogic.com/">Videos de Youtube</a></li>
								</ul>
								<div class="clear"></div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
</body>


</html>